working_directory = "/Users/azamie"

[window]
padding = { x = 12, y = 8 }
dynamic_padding = false
opacity = 0.9
decorations = "Buttonless"
title = "Alacritty"
class = { instance = "Alacritty", general = "Alacritty" }

[scrolling]
history = 5000

[font]
size = 14.0
offset = { x = 0, y = 1 }
normal = { family = "FiraCode Nerd Font", style = "Regular"}
bold = { family = "FiraCode Nerd Font", style = "SemiBold"}
italic = { family = "FiraCode Nerd Font", style = "Italic"}
bold_italic = { family = "FiraCode Nerd Font", style = "SemiBold Italic"}

[mouse]
bindings = [
  { mouse = "Middle", action = "PasteSelection"}
]

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "Insert", mods = "Shift", action = "PasteSelection" },
  { key = "Key0", mods = "Control", action = "ResetFontSize" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "F11", mods = "Control", action = "ToggleFullscreen" },
  { key = "Paste", mods = "None", action = "Paste" },
  { key = "Copy", mods = "None", action = "Copy" },
  { key = "L", mods = "Control", action = "ClearLogNotice" },
  { key = "PageUp", mods = "None", action = "ScrollPageUp", mode = "~Alt" },
  { key = "PageDown", mods = "None", action = "ScrollPageDown", mode = "~Alt" },
  { key = "Home", mods = "Shift", action = "ScrollToTop", mode = "~Alt" },
  { key = "End", mods = "Shift", action = "ScrollToBottom", mode = "~Alt" }
]
